#!/usr/bin/env python3
"""Generate the typed service catalogue source from the approved CSV export."""

from __future__ import annotations

import csv
import json
import re
import sys
from pathlib import Path


FIELDS = {
    "Category": "category",
    "Service": "service",
    "Description": "description",
    "One-off Cost (AUD)": "oneOffCostAud",
    "Monthly Cost (AUD)": "monthlyCostAud",
    "Media / Month (AUD)": "mediaMonthlyCostAud",
    "Media Editable": "mediaEditable",
    "Media Locked": "mediaLocked",
    "Delivery Qty": "deliveryQuantity",
    "Delivery Unit": "deliveryUnit",
    "Dependencies": "dependencies",
    "Recurrence Pattern": "recurrencePattern",
    "Note": "note",
}


def parse_money(value: str) -> int:
    cleaned = re.sub(r"[^0-9.-]", "", value)
    return round(float(cleaned) * 100) if cleaned else 0


def parse_number(value: str) -> int:
    return max(0, int(float(value))) if value.strip() else 0


def parse_bool(value: str) -> bool:
    return value.strip().lower() in {"true", "yes", "1"}


def normalize_row(row: dict[str, str]) -> dict[str, object]:
    missing = [column for column in FIELDS if column not in row]
    if missing:
        raise ValueError(f"CSV is missing required column(s): {', '.join(missing)}")

    return {
        "category": row["Category"].strip(),
        "service": row["Service"].strip(),
        "description": row["Description"].strip(),
        "oneOffCostCents": parse_money(row["One-off Cost (AUD)"]),
        "monthlyCostCents": parse_money(row["Monthly Cost (AUD)"]),
        "mediaMonthlyCostCents": parse_money(row["Media / Month (AUD)"]),
        "mediaEditable": parse_bool(row["Media Editable"]),
        "mediaLocked": parse_bool(row["Media Locked"]),
        "deliveryQuantity": parse_number(row["Delivery Qty"]),
        "deliveryUnit": row["Delivery Unit"].strip().lower(),
        "dependencies": row["Dependencies"].strip(),
        "recurrencePattern": row["Recurrence Pattern"].strip(),
        "note": row["Note"].strip(),
    }


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit(
            "Usage: import-service-templates.py <source.csv> <service-templates.generated.ts>"
        )

    source = Path(sys.argv[1])
    destination = Path(sys.argv[2])
    with source.open(encoding="utf-8-sig", newline="") as handle:
        rows = [normalize_row(row) for row in csv.DictReader(handle)]

    if not rows:
        raise ValueError("The service template CSV contains no services.")
    if any(not row["category"] or not row["service"] for row in rows):
        raise ValueError("Every service requires a category and service name.")

    payload = json.dumps(rows, ensure_ascii=False, indent=2)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        "/* This file is generated by scripts/import-service-templates.py. */\n"
        "import type { RawServiceTemplate } from \"./deliverable-catalog\";\n\n"
        f"export const RAW_SERVICE_TEMPLATES = {payload} satisfies RawServiceTemplate[];\n",
        encoding="utf-8",
    )
    print(f"Generated {len(rows)} service templates at {destination}")


if __name__ == "__main__":
    main()
