// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  const supabaseFetch = (input: URL | RequestInfo, init?: BunFetchRequestInit | RequestInit) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };

  return Object.assign(supabaseFetch, {
    preconnect:
      typeof fetch !== "undefined" && "preconnect" in fetch
        ? (fetch as unknown as { preconnect: typeof fetch.preconnect }).preconnect.bind(fetch)
        : ((() => Promise.resolve()) as unknown as typeof fetch.preconnect),
  });
}

function createSupabaseAdminClient() {
  const serverBuildEnv = import.meta.env as Record<string, string | undefined>;
  const SUPABASE_URL =
    process.env.SUPABASE_URL ?? serverBuildEnv.SUPABASE_URL ?? serverBuildEnv.VITE_SUPABASE_URL;
  const SUPABASE_ADMIN_KEY =
    process.env.SUPABASE_SERVICE_ROLE_KEY ??
    process.env.SUPABASE_SECRET_KEY ??
    serverBuildEnv.SUPABASE_SERVICE_ROLE_KEY ??
    serverBuildEnv.SUPABASE_SECRET_KEY;

  if (!SUPABASE_URL || !SUPABASE_ADMIN_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_ADMIN_KEY ? ["SUPABASE_SERVICE_ROLE_KEY or SUPABASE_SECRET_KEY"] : []),
    ];
    const message = `Missing server-side Supabase environment variable(s): ${missing.join(", ")}. Lovable Cloud secrets are not copied into local development automatically; add the server secret to the local environment or use the Lovable preview.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ADMIN_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_ADMIN_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
